### ISSUE TITLE
Better way to close child processes 

### ISSUE THREAD

**Issue by monkburger** [pandax381/ngx_http_pipelog_module#18]
Instead of having a prctl() DEATHSIG installed in the children (which is Linux only), we should maybe use a custom signal handler and do a raise(SIGTERM) on exit_process, and perform a _exit(0) within the handler. When I comment out the prctl() routines, the child processes are left behind with open file descriptors and a pipe. Apache's piped logging behavior does this, In httpd-2.4.52/server/log.c:

```
static apr_status_t piped_log_cleanup(void *data)
{
    piped_log *pl = data;

    if (pl->pid != NULL) {
        apr_proc_kill(pl->pid, SIGTERM);
    }
    return piped_log_cleanup_for_exec(data);
}

static apr_status_t piped_log_cleanup_for_exec(void *data)
{
    piped_log *pl = data;

    apr_file_close(pl->read_fd);
    apr_file_close(pl->write_fd);
    return APR_SUCCESS;
}

````

To reproduce, simply call cat with no data within pipelog_module, and it will wait for data (forever). Then nginx -s reload, and the FDs/pipe are still open even after the parent goes away

SIGKILL is quite destructive and graceful shutdowns (SIGTERM) should be used intead?

**Comment by monkburger** [comment]
Around +1945:

```
   if (pipe(pipelog->pim->fd) < 0) {
        ngx_conf_log_error(NGX_LOG_EMERG, cf, 0, "pipe(): error");
     	return NGX_CONF_ERROR;
    }
```
Looks like it creates a pipe. We could close the pipes in exit_process which would cause the piped logger program(s) to get EOF, and quit? Which would require us to store the pipes in a array. 

That would *probably* solve the use of DEATHSIG (we could remove it)

**Comment by pandax381** [comment]
It may be that the settings made to ignore `SIGPIPE` in `sigaction()` are inherited after `execvp()`, which may be causing the problem.

It looks like we need to change the `SIGPIPE` behavior back to `SIG_DFL` before `execvp()` in `ngx_http_pipelog_command_exec()`.

Sorry, Can you please have them try?

**Comment by monkburger** [comment]
I'll play around with it on my test environment and report back.

**Comment by monkburger** [comment]
So initial findings:

I tested this out on all versions before the recent PRs that were merged - the behavior is still present.
