### ISSUE TITLE
Crashing after latest PR (https://github.com/pandax381/ngx_http_pipelog_module/pull/22) 

### ISSUE THREAD

**Issue by monkburger** [pandax381/ngx_http_pipelog_module#23]
Looks like the recent changes are crashing:

```
(gdb) frame 0
#0  0x00007fc87c81a246 in ngx_http_pipelog_command_exec (w=w@entry=0x5638ec24e368, rfd=<optimized out>, cycle=cycle@entry=0x5638ec241980) at ngx_http_pipelog_module/ngx_http_pipelog_module.c:2266
2266	        execvp(w->we_wordv[0], w->we_wordv);
(gdb) l
2261	                close(fd);
2262	            }
2263	        }
2264	        sigfillset(&mask);
2265	        sigprocmask(SIG_UNBLOCK, &mask, NULL);
2266	        execvp(w->we_wordv[0], w->we_wordv);
2267	        exit(1);
2268	    default:
2269	        break;
2270	    }
(gdb)

```
Looks like on my test server, w->we_wordv[0] is NULL (line 2266 in the above)

https://github.com/pandax381/ngx_http_pipelog_module/pull/22/commits/e60a7ac90cf072dc7dbfe85bf4257af74b430cdb doesn't crash, but https://github.com/pandax381/ngx_http_pipelog_module/commit/d5519ffe5d34bd89253a527505596e89a26bbf03 does

**Comment by pandax381** [comment]
Oops... Sorry for not checking.
I think it is caused by wordfree() of pim->w in ngx_http_pipelog_set_log().

**Comment by pandax381** [comment]
wordfree() is not necessary because pim->w is held until the end of the program.

**Comment by monkburger** [comment]
I didn't check either, I apologize. I have some automatic test stuff that automatically grabs the latest code from your branch and tests it out. 

I'll look at removing wordfree() from the commit and submit a PR
