### ISSUE TITLE
constant respawn/reap alert

### ISSUE THREAD

**Issue by drmuey** [pandax381/ngx_http_pipelog_module#5]
Config:

```
pipelog_format bytesvhost '$server_name $msec $request_length .\n$server_name $msec $bytes_sent .'; 

pipelog_format combinedvhost '$server_name:$server_port $remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent"';

pipelog "/usr/local/cpanel/bin/splitlogs --dir=/var/log/nginx/domains --main=my.example.host --suffix=-bytes_log" bytesvhost;
pipelog "/usr/local/cpanel/bin/splitlogs --dir=/var/log/nginx/domains --main=my.example.host --mainout=/var/log/nginx/access.log" combinedvhost;
```

Do a hit:

1. The log that `splitlogs` would eventually write to are written
2. the error.log has a constant flow of message like this:

```
2019/09/11 08:57:48 [alert] 26821#19832: ngx_http_pipelog_module: respawn child process (pid='20792')
2019/09/11 08:57:48 [alert] 26821#19832: ngx_http_pipelog_module: respawn child process (pid='20793')
2019/09/11 08:57:48 [alert] 26821#19832: ngx_http_pipelog_module: reap child process (pid='20792'), respawn child process after 1 sec
2019/09/11 08:57:48 [alert] 26821#19832: ngx_http_pipelog_module: reap child process (pid='20793'), respawn child process after 1 sec
```

Is there a way to prevent this?

**Comment by pandax381** [comment]
Hi, drmuey!

> pipelog command [format [nonblocking] [if=condition]];

`command` in the pipelog directive is finally expanded as follows:

```
/bin/sh -c command
```

pipelog module executes the above command via fork(2) execvp(3).

Then, pipelog module keeps outputting logs to the STDIN of commands.
Invoked command is expected to continue reading the log from STDIN.

If the command ends, the pipelog module will respawn the command.
Is the `splitlogs` always running as long as the log continues to be sent to STDIN?

**Comment by drmuey** [comment]
Actually, it is working now after a general update, so the  loop was probably a local issue. Thanks!

And thanks for making this very handy module 👍
