### ISSUE TITLE
stale piped logging processes

### ISSUE THREAD

**Issue by drmuey** [pandax381/ngx_http_pipelog_module#7]
1. Start w/ a fresh restart w/ appropriate processes
```
# echo "nginx processes: $(ps faux | grep -c nginx)" && echo "splitlog processes: $(ps faux | grep -c splitlogs)";
nginx processes: 6
splitlog processes: 5
# 
```
2. Send HUPs (akin to a reload)
```
for i in {1..10}; do /bin/kill -s HUP $(cat /var/run/nginx.pid) && echo "restart $i" && echo "nginx processes: $(ps faux | grep -c nginx)" && echo "splitlog processes: $(ps faux | grep -c splitlogs)"; done
```
3. Notice that the process count will grow each time it receives SIGHUP:
```
restart 1
nginx processes: 6
splitlog processes: 4
restart 2
nginx processes: 5
splitlog processes: 5
restart 3
nginx processes: 6
splitlog processes: 5
restart 4
nginx processes: 5
splitlog processes: 5
restart 5
nginx processes: 5
splitlog processes: 4
restart 6
nginx processes: 5
splitlog processes: 4
restart 7
nginx processes: 6
splitlog processes: 4
restart 8
nginx processes: 6
splitlog processes: 4
restart 9
nginx processes: 6
splitlog processes: 4
restart 10
nginx processes: 5
splitlog processes: 5
… run a few more times …
restart 1
nginx processes: 30
splitlog processes: 20
restart 2
nginx processes: 29
splitlog processes: 21
restart 3
nginx processes: 30
splitlog processes: 21
restart 4
nginx processes: 30
splitlog processes: 21
restart 5
nginx processes: 30
splitlog processes: 21
restart 6
nginx processes: 29
splitlog processes: 21
restart 7
nginx processes: 30
splitlog processes: 21
restart 8
nginx processes: 29
splitlog processes: 21
restart 9
nginx processes: 30
splitlog processes: 21
restart 10
nginx processes: 29
splitlog processes: 21
```
3. w/out ngx_http_pipelog_module in palay the SIGHUPs do not result in increased nginx processes

This is on CentOS 6 and 7 w/ `nginx` v1.17.3 and `ngx_http_pipelog_module` at 68b5f4b655.

----

Some notes:

1. sometimes a hard stop clears them, and sometimes it clears one of the two which is magically tied to port 80 but not actually doing HTTP
2. On a test server with 100 users (1 conf file per user) this does not happen, presumably taking long enough to win the race
3. ON a test server with 1 user this does happen, presumably fast enough to lose the race

**Comment by pandax381** [comment]
Thank you for your feedback.

Sorry, this module does not support nginx's graceful restart (ie restart with SIGHUP).

I will check if I can take measures when I have time.

**Comment by drmuey** [comment]
Sounds great, thanks!

**Comment by drmuey** [comment]
I see this was closed, was it fixed?

**Comment by drmuey** [comment]
Following up in #10 👍👍
