### ISSUE TITLE
Bringing back `nginx: logger process`

### ISSUE THREAD

**Issue by drmuey** [pandax381/ngx_http_pipelog_module#8]
Greetings!

If I start with a working pipelog setup:

```
nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
nginx: worker process
nginx: logger process
… processes from the pipelog directives …
```
and then:

1. do some hits
2. flush the logs to disk
3. see that the hits were logged
4. simulate a bad event: kill -9 the processes from the pipelog directives
5. `nginx: logger process` starts up new ones automatically
6. simulate a bad event: kill -9 `nginx: logger process`
7. it never comes back
8. a restart or reload does not bring it back
9. a hard stop and then start will result in all being back in good shape

Is there any way to get `nginx: logger process` besides a hard stop/start?

I’ve tried sending some signals to nginx but haven’t found any that have it bring back an `nginx: logger process`.

Thanks!

**Comment by pandax381** [comment]
Yes, it's a specification.

The logger process automatically restores the process of the pipelog directive, but it does not automatically recover if the logger process itself exits unexpectedly.

The logger process is started only once, when nginx starts.
