### ISSUE TITLE
Logs go to piped program and access.log

### ISSUE THREAD

**Issue by drmuey** [pandax381/ngx_http_pipelog_module#9]
Is there a way to configure it to only go to access.log for requests that are not configured for the piped logging?

thanks!

**Comment by drmuey** [comment]
of note, we are not defining `access_log` anywhere. Only global `error_log`, `log_format`, `pipelog_format`, and `pipelog`.

I don’t think it’d be advisable to globally `access_log off;` when using `pipelog`.

**Comment by pandax381** [comment]
The pipelog works independent from access_log.
I'm assuming that access_log is off, but it should be fine to run them in parallel.

And if you want to control the log output to pipelog and access_log, you need to write a configuration to do it.
If you want to control whether the output goes to the pipelog or access_log, you can use `if=condition`. It's supported by both access_log and pipelog.
